name: "Build"
on:
  push:
    branches:
    - "!dependabot/*"
    - "*"
  pull_request:
    branches:
    - "*"
jobs:
  lint: 
    name: "Lint"
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v2"
    - uses: "bufbuild/buf-setup-action@v0.5.0"
      with:
        version: "0.48.2"
    - uses: "bufbuild/buf-lint-action@v1"
    - uses: "bufbuild/buf-breaking-action@v0.4.0"
      if: "github.event_name == 'pull_request'"
      env:
        BUF_INPUT_HTTPS_USERNAME: "${{ github.actor }}"
        BUF_INPUT_HTTPS_PASSWORD: "${{ github.token }}"
      with:
        against: "https://github.com/authzed/api.git#branch=main"
        buf_token: "${{ secrets.BUF_REGISTRY_TOKEN }}"
    - uses: "bufbuild/buf-push-action@v0.3.0"
      if: "github.event_name == 'push'"
      with:
        buf_token: "${{ secrets.BUF_REGISTRY_TOKEN }}"
