name: "Manually invoke client updates for API change"
on:
  workflow_dispatch:
    inputs:
      buftag:
        description: "Tag or commit from https://buf.build/authzed/api/tags/main"
        required: true
        type: "string"
jobs:
  trigger:
    runs-on: "ubuntu-latest"
    name: "📦 Trigger Client Updates"
    steps:
      - uses: "passeidireto/trigger-external-workflow-action@main"
        env:
          PAYLOAD_BUFTAG: "${{ inputs.buftag }}"
        with:
          repository: "authzed/authzed-node"
          event: "api_update"
          github_pat: "${{ secrets.EXTERNAL_REPO_TOKEN }}"
