---
name: "Manually invoke client updates for API change"
on:
  workflow_dispatch:
    inputs:
      buftag:
        description: "Tag or commit from https://buf.build/authzed/api/tags/main"
        required: true
        type: "string"
jobs:
  trigger:
    runs-on: "ubuntu-latest"
    name: "📦 Trigger Client Updates"
    steps:
      - uses: "peter-evans/repository-dispatch@v2"
        name: "🕸️ Update authzed-node"
        with:
          token: "${{ secrets.EXTERNAL_REPO_TOKEN }}"
          repository: "authzed/authzed-node"
          event-type: "api_update"
          client-payload: '{"BUFTAG": "${{ inputs.buftag }}"}'
      - uses: "peter-evans/repository-dispatch@v2"
        name: "🐍 Update authzed-py"
        with:
          token: "${{ secrets.EXTERNAL_REPO_TOKEN }}"
          repository: "authzed/authzed-py"
          event-type: "api_update"
          client-payload: '{"BUFTAG": "${{ inputs.buftag }}"}'
      - uses: "peter-evans/repository-dispatch@v2"
        name: "💎 Update authzed-rb"
        with:
          token: "${{ secrets.EXTERNAL_REPO_TOKEN }}"
          repository: "authzed/authzed-rb"
          event-type: "api_update"
          client-payload: '{"BUFTAG": "${{ inputs.buftag }}"}'
      - uses: "peter-evans/repository-dispatch@v2"
        name: "☕ Update authzed-java"
        with:
          token: "${{ secrets.EXTERNAL_REPO_TOKEN }}"
          repository: "authzed/authzed-java"
          event-type: "api_update"
          client-payload: '{"BUFTAG": "${{ inputs.buftag }}"}'
