---
name: "Release"
on:  # yamllint disable-line rule:truthy
  push:
    tags:
      - "*"
jobs:
  buf:
    name: "Push BSR tag"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "bufbuild/buf-setup-action@v1"
        with:
          version: "1.4.0"
      - uses: "bufbuild/buf-push-action@v1"
        with:
          buf_token: "${{ secrets.BUF_REGISTRY_TOKEN }}"
